In [57]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [58]:
import numpy as np

In [59]:
np.zeros(3)

array([0., 0., 0.])

In [60]:
type(np.zeros(3))

numpy.ndarray

In [61]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [64]:
np.empty((3, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.24101497e-321],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [65]:
np.full(3, 255)

array([255, 255, 255])

In [66]:
np.random.rand(2, 5)

array([[0.98145143, 0.39507006, 0.91940941, 0.63843165, 0.62935621],
       [0.94906671, 0.83309711, 0.96343508, 0.84146381, 0.33276701]])

In [67]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int)

array([[6, 2, 6],
       [2, 3, 4]])

In [68]:
test_arr = np.array([2, 3, 4])
test_arr

array([2, 3, 4])

In [69]:
test_arr.ndim # 陣列列數(維度)

1

In [70]:
test_arr.shape # 陣列行數

(3,)

In [71]:
test_arr.size # 陣列內有幾個值

3

In [72]:
arr = np.random.randint(low=2, high=8, size=(2, 3), dtype=int)

In [73]:
arr.reshape((3,2))

array([[4, 3],
       [5, 6],
       [5, 6]])

In [74]:
arr.reshape((3,-1))

array([[4, 3],
       [5, 6],
       [5, 6]])

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
np.mean(arr)

3.5

In [77]:
np.median(arr)

3.5

In [78]:
np.percentile(arr, 50, method='higher')

4

In [79]:
mu = arr.mean()

In [86]:
arr - mu

array([-2.5, -1.5, -0.5,  0.5,  1.5,  2.5])

In [87]:
arr.sum()

21

In [88]:
(arr - mu).mean()

0.0

In [89]:
np.power((arr - mu), 2)

array([6.25, 2.25, 0.25, 0.25, 2.25, 6.25])

In [90]:
np.power((arr - mu), 2).mean()

2.9166666666666665

In [91]:
np.sqrt(
    np.power(
        (arr -mu), 2
    ).mean()
)

1.707825127659933

In [93]:
arr.std()

1.707825127659933

In [94]:
np.random.normal(0, 1, 10)

array([ 0.45935096, -0.4285071 , -0.10390264, -0.01853204, -1.22376876,
       -0.80815859,  0.37957196, -1.04320428, -1.80818981, -0.43512431])

In [95]:
arr > 3

array([False, False, False,  True,  True,  True])

In [97]:
~(arr > 3)

array([ True,  True,  True, False, False, False])

In [98]:
(arr > 2) & (arr < 5)

array([False, False,  True,  True, False, False])

In [106]:
a = set([3, 4, 5, 6])
b = set([4, 5, 6, 7])
print(a & b)
print(a | b)
print(a - b)
print(a ^ b)

{4, 5, 6}
{3, 4, 5, 6, 7}
{3}
{3, 7}


In [112]:
~(arr < 2) & ~(arr > 5)

array([False,  True,  True,  True,  True, False])